name: "skeleton-service"

logger:
  level: 0
  encoding: "json"

http:
  port: 8080
  healthcheck:
    path: "/health"
  profiling:
    enabled: false

metrics:
  enabled: true
  path: "/metrics"
  namespace: ""
