// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package ports

// Error defines model for Error.
type Error struct {

	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// NewUser defines model for NewUser.
type NewUser struct {

	// Name of the user
	Name string `json:"name"`

	// Type of the user
	Tag *string `json:"tag,omitempty"`
}

// User defines model for User.
type User struct {
	// Embedded struct due to allOf(#/components/schemas/NewUser)
	NewUser `yaml:",inline"`
	// Embedded fields due to inline allOf schema

	// Unique id of the user
	Id string `json:"id"`
}

// AddUserJSONBody defines parameters for AddUser.
type AddUserJSONBody NewUser

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody AddUserJSONBody
