name: publish

on:
  workflow_run:
    workflows: ["test"]
    types: 
      - completed


jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Build
        run: |
          docker build .
